### PR TITLE
Refactored documentation and added /stats api docs

### PR DESCRIPTION
**Pull request by dyladan**
Broke up the API documentation into multiple files to make it easier to navigate and read

Documented /stats/users and /stats/bookmarks to at least a useable level

made table of contents :maxdepth: 2 in order to improve navigability

### CODE REVIEW

**Comment by mitechie** [comment]
The table of contents on the main page is a bit off in the development section. It reads "Working on signup process" and then "Content"

**Comment by mitechie** [comment]
Generally this is a good step. There's lots that can be cleaned up looking at the docs in all. The issue above should be updated though before landing.

**Comment by dyladan** [comment]
# Refactored API documentation
- added /stats/users and /stats/bookmarks to the system wide calls section of the API docs
- With API documentation split into sections by file it is more readable and easier to navigate than a single huge file
- put API documentation files into api folder
- made table of contents have a maxdepth of 2
- added emailserver to development toctree
- removed working on signup process heading
- reformatted makefile.rst
- added features.rst to main toctree
- marked test.rst#test-types as out of date

This fixes the comment @mitechie made earlier regarding `Contents:` being in the toctree

Squashed all into a single commit rebased off of bookieio develop branch.

**Comment by dyladan** [comment]
to see this branch built check out http://bdocs.dyladan.me

**Comment by mitechie** [comment]
Thanks, looks good. 

:shipit:

**Pull request merged**
