### PR TITLE
issue #266

### PR DESCRIPTION
**Pull request by preddy5**

### CODE REVIEW

**Comment by preddy5** [comment]
"Some of it is textual.
- Bookie isn't alpha, that note should be pulled out
- You don't need an invite to get into bookie any more. That should be pulled out
- Once you click the activate link in your email and set a password, bookie should auto log you in and show you the page for your bookmarks."

1,2 done, i think 3 is already in place

**Comment by preddy5** [comment]
@mitechie what more edits are needed?

**Comment by sambuddhabasu** [comment]
I have tested the code. The code seems to run fine. Activation emails are sent as expected with the desired message. make lint is clean.
As far as the three points go, 1 and 2 have been fixed with the current pull request and 3 has been already taken care of before.

**Comment by mitechie** [comment]
Thanks for helping to polish things up and thanks for the QA Sambuddha.

**Pull request closed without merging**
