### PR TITLE
Bookmark count for individual user with tests

### PR DESCRIPTION
**Pull request by sambuddhabasu**

### CODE REVIEW

**Comment by sambuddhabasu** [comment]
Fixed issue #87

**Comment by mitechie** [comment]
I've landed this with some updates.
- I've used the existing UserMgr.get_list(active=True) to find the users. Finding a list of users should be the UserMgr's job, not Bmarks.
- I've tweaked the stats method to not do the query. The stats should know as little as possible and only deal with the stats database. The username is passed in now from the task and it only saves a stats record and does not touch other areas of the db.
- Updated the test to check that the numbers for all three sample users are correct.

**Comment by mitechie** [comment]
This is now running in production on bmark.us

**Comment by sambuddhabasu** [comment]
Thanks and thats some great news!

**Pull request closed without merging**
