### PR TITLE
Added test for duplicate tags. Added animation.

### PR DESCRIPTION
**Pull request by suryatech**
Modified tests to prevent race situations. Used wait construct instead.

### CODE REVIEW

**Comment by sambuddhabasu** [comment]
Tested the pull request. The JS tests run fine. make lint is clean.
@mitechie Do let me know if I am missing any other step for testing the code.

**Comment by suryatech** [comment]
@sammyshj : Thanks for your time. What do you think about the animation. Is 0.1 s fine or should it be increased/decreased?

**Comment by mitechie** [comment]
Thanks for this, since the original issue in #198 was that Bookie removed the dupe and it wasn't clear why, I slowed it down to .4s so that it's obvious that there's something going on and the user hopefully puts it all together now. 

Thanks for the branch, the tests, and your patience as it all got worked out.

**Comment by suryatech** [comment]
Great! I thought that a larger duration might make it 'appear' slow. Anyways, thanks for the change.

**Pull request closed without merging**
