### PR TITLE
Add requirements for dependencies of breadability 0.1.15

### PR DESCRIPTION
**Pull request by mazz**

### CODE REVIEW

**Comment by mitechie** [comment]
Thanks for the pull request. This diff seems to be missing the breadability version to 0.1.15. Can you double check and update it?

**Comment by mazz** [comment]
I'm assuming it's ok because currently the criteria is `breadability < 0.2`

**Comment by mitechie** [comment]
Thanks, in testing this there are a 5 tests having issues with these dep changes. I'll have to chase them down before merging this into the main line of development.

**Comment by mitechie** [comment]
This has been merged manually. I've updated the code/tests and all is well. I'll try to update the deploy on bmark.us later this week!

**Pull request closed without merging**
